version: 2

jobs:

  test:
    docker:
      - image: circleci/rust:1.37.0-stretch
    steps:
      - checkout
      # https://circleci.com/docs/2.0/caching/
      - restore_cache:
          keys:
            - tnetstring-v2-{{ .Branch }}-{{ checksum "Cargo.lock" }}
            - tnetstring-v2-{{ .Branch }}-
            - tnetstring-v2-
      - run:
          name: run lints
          command: |
            cargo test
      - save_cache:
          paths:
            - ~/.cargo/
          key: tnetstring-v2-{{ .Branch }}-{{ checksum "Cargo.lock" }}

  lint:
    docker:
      - image: circleci/rust:1.37.0-stretch
    steps:
      - checkout
      # https://circleci.com/docs/2.0/caching/
      - restore_cache:
          keys:
            - tnetstring-v2-{{ .Branch }}-{{ checksum "Cargo.lock" }}
            - tnetstring-v2-{{ .Branch }}-
            - tnetstring-v2-
      - run:
          name: install dependencies
          command: |
            rustup update
            rustup component add clippy-preview
            rustup component add rustfmt-preview
      - run:
          name: run lints
          command: |
            cargo clippy -- -Dwarnings
            cargo fmt
      - save_cache:
          paths:
            - ~/.cargo/
          key: tnetstring-v2-{{ .Branch }}-{{ checksum "Cargo.lock" }}

workflows:
  version: 2
  test:
    jobs:
      - test
      - lint
